=== nicole-an9elova/FMI-XML-2020/guitarCatalogue.dtd
<!ELEMENT catalogue (name, products)>
	<!ELEMENT name (#PCDATA)>
    <!ELEMENT products (product+)>
		<!ELEMENT product (nameOfTheProduct, picture, descriptionOfProduct,
				features*, warranty, price, version)>
			<!ATTLIST product certificate (Yes | No) "No"
								returns (Yes|No) "No">
			<!ELEMENT nameOfTheProduct (#PCDATA)> 
			<!ELEMENT picture (#PCDATA)>
				<!ATTLIST picture size NMTOKEN #REQUIRED
								  pictureAltText #PCDATA #REQUIRED>
			<!ELEMENT descriptionOfProduct (#PCDATA)> 
			<!ELEMENT features (body, neck, electronics, hardware, miscellaneous, accessories)>
				<!ELEMENT body (bodyMaterial, bodyShape, bodyFinish)>
					<!ELEMENT bodyMaterial (#PCDATA)>
					<!ELEMENT bodyShape (#PCDATA)>
					<!ELEMENT bodyFinish (#PCDATA)>
				<!ELEMENT neck (neckMaterial, neckFinish, neckShape, scaleLength, fingerboardMaterial, fingerboardRadius,
						numberOfFrets, fretSize, nutMaterial, nutWidth, positionInlays, trussRod)
					<!ELEMENT neckMaterial (#PCDATA)>
					<!ELEMENT neckFinish (#PCDATA)>
					<!ELEMENT neckShape (#PCDATA)>
					<!ELEMENT scaleLength (#PCDATA)>
					<!ELEMENT fingerboardMaterial (#PCDATA)>
					<!ELEMENT fingerboardRadius (#PCDATA)>
					<!ELEMENT numberOfFrets (#PCDATA)>
					<!ELEMENT fretSize (#PCDATA)>
					<!ELEMENT nutMaterial (#PCDATA)>
					<!ELEMENT nutWidth (#PCDATA)>
					<!ELEMENT positionInlays (#PCDATA)>
					<!ELEMENT trussRod (#PCDATA)>
				<!ELEMENT electronics (neckPickup, controls, switching, configuration)>
					<!ELEMENT neckPickup (#PCDATA)>
					<!ELEMENT controls (#PCDATA)>
					<!ELEMENT switching (#PCDATA)>
					<!ELEMENT configuration (#PCDATA)>
				<!ELEMENT hardware (bridge, hardwareFinish, tuningMachines, pickguard, controlKnobs, neckPlate)
					<!ELEMENT bridge (#PCDATA)>
					<!ELEMENT hardwareFinish (#PCDATA)>
					<!ELEMENT tuningMachines (#PCDATA)>
					<!ELEMENT pickguard (#PCDATA)>
					<!ELEMENT controlKnobs (#PCDATA)>
					<!ELEMENT neckPlate (#PCDATA)>
				<!ELEMENT miscellaneous (strings, legalNotice)>
					<!ELEMENT strings (#PCDATA)>
					<!ELEMENT legalNotice (#PCDATA)>
				<!ELEMENT accessories (#PCDATA)>
					<!ATTLIST accessories gigBag (Yes | No) "No"
										  guitarPicks CDATA #REQUIRED >
			<!ELEMENT warranty (#PCDATA)>
			<!ELEMENT price (#PCDATA)> 
			<!ELEMENT version (#PCDATA)>

=== nicole-an9elova/FMI-XML-2020/catalogue_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalogue_html_1.xsl"?>
<!DOCTYPE catalogue SYSTEM "guitarCatalogue.dtd">

<catalogue>
    <name>EPIPHONE</name>
    <products>
        <product certificate="Yes" returns="No">
            <nameOfTheProduct>ES-335 Figured</nameOfTheProduct>
            <picture size="2" pictureAltText="Снимка на лицевата страна на китарата">images/epiphone_1.png
            </picture>
            <descriptionOfProduct>
                Още една музикална легенда може да оживее в ръцете ви, чрез моделът на Epiphone, 
                който пресъздава оригинала на Гибсън ES-335 Dot. Моделът надминава всички имитации
                като осигурява за китаристите от съвременното поколение класическата визия въплътена
                в голямото полу-акустично тяло. Това, което е различно обаче, е цената.
                За тази китара не плащате натрупаната в нея история.
                На супер цена получавате Epiphone ЕS-335 Figured в пламтящ червено-син цвят, с черна
                финитура по периметъра на тялото.
            </descriptionOfProduct>
            <features>
                <body>
                    <bodyMaterial>Слоен клен</bodyMaterial>
                    <bodyShape>ES-335 Singlecut</bodyShape>
                    <bodyFinish>Многослоен клен, пламъчен фурнир AAA</bodyFinish>
                </body>
                <neck>
                    <neckMaterial>Махагон</neckMaterial>
                    <neckFinish>Сатенен уретан с гланцово уретаново лице</neckFinish>
                    <neckShape>Закръглена C</neckShape>
                    <scaleLength>24,72 "/ 628 мм</scaleLength>
                    <fingerboardMaterial>Индийски лавр</fingerboardMaterial>
                    <fingerboardRadius>12.01"</fingerboardRadius>
                    <numberOfFrets>22</numberOfFrets>
                    <fretSize>Medium Jumbo</fretSize>
                    <nutMaterial>Graph Tech® NuBone®</nutMaterial>
                    <nutWidth>1,69 "/ 43 мм</nutWidth>
                    <positionInlays>Малък блок</positionInlays>
                    <trussRod>Залепена, зададена врата</trussRod>
                </neck>
                <electronics>
                    <neckPickup>Мост Alnico Classic PRO</neckPickup>
                    <controls>Основна сила на звука, Pan Pot (селектор), Treble Boost / Cut, Midrange Boost / Cut, Bass Boost / Cut, Passive Tone, Active / Passive Mini Toggle</controls>
                    <switching>Никакво</switching>
                    <configuration>PJ</configuration>
                </electronics>
                <hardware>
                    <bridge>Epiphone LockTone ™ Tune-O-Matic ™</bridge>
                    <hardwareFinish>Никел</hardwareFinish>
                    <tuningMachines>Epiphone Deluxe</tuningMachines>
                    <pickguard>3-слойно ментово зелено</pickguard>
                    <controlKnobs>Копчета за черна шапка с метални вложки</controlKnobs>
                    <neckPlate>5-болтна</neckPlate>
                </hardware>
                <miscellaneous>
                    <strings>.010, .013, .017, .026, .036, .046</strings>
                    <legalNotice>Рак и репродуктивно увреждане - www.P65Warnings.ca.gov .</legalNotice>
                </miscellaneous>
                <accessories gigBag="Yes" guitarPicks="No">Елитен калъф</accessories>
            </features>
            <warranty>Warranty.pdf</warranty>
            <price>599,00€</price>
            <version>#: 0199010732</version>
        </product>
        <product certificate="Yes" returns="Yes">
            <nameOfTheProduct>Epiphone Broadway Vintage Natural</nameOfTheProduct>
            <picture size="2" pictureAltText="Снимка на лицевата страна на китарата">images/ep_2.jpg</picture>
            <descriptionOfProduct>
                Класическа китара с кухи тела и дупка с форма на арка. 
                Корпусът на инструмента е изработен от ламинирано дърво от клен с върха на смърч.
                Шията на кленята е снабдена с гриф Pau Ferro с 20 средни Jumbo прашки.
                Китарата е оборудвана и с регулируем плаващ мост Пауро Феро, апарати за разделяне
                на трапецообразните механизми на сплит трапеца, златен хардуер и тунер Grover Rotomatic.
                В допълнение, той предлага два пикапа Alnico Classic Humbucker. 
                Звукът се настройва с помощта на два потенциометъра Tone, два потенциометъра за 
                обем и трипозиционен превключвател.Китарата е направена с Vintage Natural финиш.
            </descriptionOfProduct>
            <features>
                <body>
                    <bodyMaterial>Ламиниран клен</bodyMaterial>
                    <bodyShape>Broadway Singlecut</bodyShape>
                    <bodyFinish>Блясък, гладър фурнир BBB</bodyFinish>
                </body>
                <neck>
                    <neckMaterial>Твърд клен</neckMaterial>
                    <neckFinish>Сатенен уретан с гланцово уретаново лице</neckFinish>
                    <neckShape>Профил на SlimTaper C</neckShape>
                    <scaleLength>25.5 ""/ 636 мм</scaleLength>
                    <fingerboardMaterial>Пау Феро</fingerboardMaterial>
                    <fingerboardRadius>12"</fingerboardRadius>
                    <numberOfFrets>20</numberOfFrets>
                    <fretSize>Medium Jumbo</fretSize>
                    <nutMaterial>Graph Tech® NuBone®</nutMaterial>
                    <nutWidth>	1,6875 "</nutWidth>
                    <positionInlays>Седеф / Абалон блок и триъгълник</positionInlays>
                    <trussRod>Залепена, зададена врата</trussRod>
                </neck>
                <electronics>
                    <neckPickup>Класически Alnico Humbucker</neckPickup>
                    <controls>2 x сила на звука, 2 x тон, 3-посочен превключвател</controls>
                    <switching>Никакво</switching>
                    <configuration>KM</configuration>
                </electronics>
                <hardware>
                    <bridge>Регулируем плаващ мост Pau Ferro с фронтален трапецовиден мост</bridge>
                    <hardwareFinish>Никел</hardwareFinish>
                    <tuningMachines>Grover Rotomatic, съотношение 18: 1</tuningMachines>
                    <pickguard>3-слойно</pickguard>
                    <controlKnobs>Копчета за черна шапка с метални вложки</controlKnobs>
                    <neckPlate>4-болтна</neckPlate>
                </hardware>
                <miscellaneous>
                    <strings>.010, .013, .017, .026, .036, .046</strings>
                    <legalNotice>Рак и репродуктивно увреждане - www.P65Warnings.ca.gov .</legalNotice>
                </miscellaneous>
                <accessories gigBag="Yes" guitarPicks="Yes">Елитен калъф</accessories>
            </features>
            <warranty>Warranty.pdf</warranty>
            <price>689,00€</price>
            <version>#: 019904567</version>
        </product>
    
       
    </products>
</catalogue>

=== nicole-an9elova/FMI-XML-2020/catalogue_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalogue_html_3.xsl"?>
<!DOCTYPE catalogue SYSTEM "guitarCatalogue.dtd">
<catalogue>
    <name>PRS</name>
    <products>
        <product certificate="Yes" returns="No">
            <nameOfTheProduct>SE Custom 22</nameOfTheProduct>
            <picture size="2" pictureAltText="Снимка на лицевата страна на китарата">images/prs/prs_1.jpg</picture>
            <descriptionOfProduct>
                PRS SE Custom 22 добавя по-ретро тон и усещане към традиционната персонализирана платформа. 
                Тази китара има подчертан среден клас и яснота, която осигурява сладка, пълна тонална основа,
                позволяваща й лесно да се впише в комбинацията на вашата група или запис. Подобно на своя брат
                с 24 лана, SE Custom 22 има кленово покритие с гръб от махагон и 25-инчова скала. 
                Допълнителните ангажименти включват двойни 85/15 "S" хамбакери с обем, натискане / издърпване 
                и 3-посочен превключвател на ножовете и патентован PRS мост тремоло. 
                SE Custom 22 е солиден избор за играчи, израснали на 22 лада.
            </descriptionOfProduct>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>976,00лв.</price>
            <version>#: 0288000526</version>
        </product>
        <product certificate="No" returns="No">
            <nameOfTheProduct>SE Custom 22 Semi-Hollow</nameOfTheProduct>
            <picture size="3" pictureAltText="Снимка на лицевата страна на китарата">images/prs/prs_2.jpg</picture>
            <descriptionOfProduct>
                В PRS SE по поръчка 22 Полу-Холоу има музикален среден клас и изключително резонанс. 
                Полу-кухото тяло осигурява ефирен, сладък тон, но с завъртане на копчето за тонове, 
                двойните хамбакери могат да получат много ярки удари. Допълнителните ангажименти включват
                кленов връх, гръб и врата от махагон, гриф от розово дърво и двойни пикапи 85/15 „S“ 
                с регулиране на силата на звука и натискане / издърпване (за потупване на спирала),
                съчетани с 3-посочен селектор за вземане на острието. 85/15 „S“ 
                пикапите придават забележителна яснота и разширен висок и нисък край на гласа на този полу-кух.
            </descriptionOfProduct>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>520,00лв.</price>
            <version>#: 0288456300</version>
        </product>
        <product certificate="Yes" returns="Yes">
            <nameOfTheProduct>SE Custom 24</nameOfTheProduct>
            <picture size="3" pictureAltText="Снимка на лицевата странан на китарата">images/prs/prs_3.jpg</picture>
            <descriptionOfProduct>
                В SE обичая 24 е модерен класически с технически изправни трайност, пристрастяване игра 
                и широк спектър от цветове, което го прави идеален кон китара. Играна от международни
                 туристически артисти, концертиращи музиканти и амбициозни играчи, SE Custom 24 се 
                 отличава с кленово покритие с плитка цигулка, гръб от махагон, широка тънка шийка
                  от клен, гриф от палисандрово дърво с инкрустации за птици и патентован мост за тремоло
                   от PRS. Неговите многостранни звуци идват от пикапите 85/15 “S”, съчетани
                 с регулатор на силата на звука, пулс / дръпване на тона и 3-посочен селектор на пикапа.
            </descriptionOfProduct>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>507.00лв.</price>
            <version>#: 0288456170</version>
        </product>
        <product certificate="Yes" returns="No">
            <nameOfTheProduct>SE Custom 24 "Floyd"</nameOfTheProduct>
            <picture size="3" pictureAltText="Снимка на лицевата странан на китарата">images/prs/prs_4.jpg</picture>
            <descriptionOfProduct>
                В SE по поръчка 24 "Флойд" носи легендарния Floyd Rose моста към най-известния модел PRS е:
                 по поръчка 24. Floyd Rose 1000 Series тремоло на дава на играчите нови опции за формулировка
                  и увереност да трептене или гмуркане бомба, без да става фалшиво. Допълнителните срещи 
                  включват 24 лада, 25-инчова скала, широка тънка кленова врата и 85/15 „S“ пикапи, които
                   осигуряват забележителна яснота и удължен висок и нисък край (без кал, когато отидете за гърлото!).
                    Така че гмуркайте се, огъвайте се, играйте с хармоници и се забавлявайте с SE Custom 24 “Floyd”
                     китара ... тя може да отнеме каквото имате.
            </descriptionOfProduct>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>507.00лв.</price>
            <version>#: 0288456170</version>
        </product>
        <product certificate="No" returns="Yes">
            <nameOfTheProduct>SE Custom 24 "Lefty"</nameOfTheProduct>
            <picture size="3" pictureAltText="Снимка на лицевата странан на китарата">images/prs/prs_5.jpg</picture>
            <descriptionOfProduct>
                PRS SE Custom 24 е типичният SE инструмент, създаден да отразява вярно PRS модела,
                 който започна всичко. PRS SE Custom 24 Lefty  носи класически PRS за игра, 
                 надеждност и жив тон на левичарите по света. Готов за концерти и студиен звук,
                  този модел запазва същите основни спецификации като SE Custom 24: кленов връх,
                   гръб от махагон, широка тънка кленова шийка, 24 лада, 25-инчова дължина, PRS 
                   патентован формован тремоло и двоен 85 / 15 „S“ пикапи с 3-посочен превключвател 
                   на острието и управление на тона за натискане / издърпване за почукване на намотка. 

            </descriptionOfProduct>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>507.00лв.</price>
            <version>#: 0288456170</version>
        </product>
    </products>
</catalogue>

=== nicole-an9elova/FMI-XML-2020/catalogue_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalogue_html_2.xsl"?>
<!DOCTYPE catalogue SYSTEM "guitarCatalogue.dtd">
<catalogue>
    <name>IBANEZ</name>
    <products>
        <product certificate="Yes">
            <nameOfTheProduct>JEMJR</nameOfTheProduct>
            <picture size="2" pictureAltText="Снимка на лицевата страна на китарата">images/ibanez/JEMJR_front.jpg</picture>
            <descriptionOfProduct>
                Eлектрическа китара – модел Ibanez JEMJR WH. Иначе казано,
                това e легендарният Jam в конфигурация junior, бюджетен модел,
                който идва на отлична цена. Китарата е част от моделите на Steve Vai,
                с характерната дръжка в горната част на тялото, декорирания гриф с красивия
                флорален мотив (дървото на живота) и марковото тремоло в стил лъвски нокът.
                От списанието Guitar Player определят китарата като добре изглеждаща,
                с много удобен гриф за бързо свирене и е китара на цена,
                която могат да си позволят и начинаещи китаристи. От 2018 г. китарата е на пазара
                с някои нововъведения в структурата, които я правят още по-качествен модел.
            </descriptionOfProduct>
            <features>
                <body>
                    <bodyMaterial>Махагон</bodyMaterial>
                    <bodyShape>Солидна</bodyShape>
                    <bodyFinish>Гланц Полиуретан</bodyFinish>
                </body>
                <neck>
                    <neckMaterial>Клен</neckMaterial>
                    <neckFinish>Сатенен уретан с гланцово уретаново лице</neckFinish>
                    <neckShape>Bolt-On Neck</neckShape>
                    <scaleLength>25.5" / 64.77 cm</scaleLength>
                    <fingerboardMaterial>Палисандрово дърво</fingerboardMaterial>
                    <fingerboardRadius>15.7"</fingerboardRadius>
                    <numberOfFrets>24</numberOfFrets>
                    <fretSize>Jumbo</fretSize>
                    <nutMaterial>Костен</nutMaterial>
                    <nutWidth>(43 mm)</nutWidth>
                    <positionInlays>8мм</positionInlays>
                    <trussRod>None</trussRod>
                </neck>
                <electronics>
                    <neckPickup>Humbucker</neckPickup>
                    <controls>Tone Control: x1
                        Volume Control: x1
                    </controls>
                    <switching>5-Way Pickup Selector Switch</switching>
                    <configuration>PK</configuration>
                </electronics>
                <hardware>
                    <bridge>(Passive/Ceramic)</bridge>
                    <hardwareFinish>Черен цвят</hardwareFinish>
                    <tuningMachines>No</tuningMachines>
                    <pickguard>3-слойно черен/бял</pickguard>
                    <controlKnobs>Плосък връх, Бял тон</controlKnobs>
                    <neckPlate>Cavity plate, Jack Black</neckPlate>
                </hardware>
                <miscellaneous>
                    <strings>10.5mm разстояние между 6-те Ibanez струни</strings>
                    <legalNotice>
                        ПРЕДУПРЕЖДЕНИЕ: Рак и репродуктивно увреждане - www.P65Warnings.ca.gov .
                    </legalNotice>
                </miscellaneous>
                <accessories gigBag="Yes" guitarPicks="No">Елитен калъф</accessories>
            </features>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>976,00лв.</price>
            <version>#: 0288000526</version>
        </product>
        <product certificate="Yes" returns="No">
            <nameOfTheProduct>IBANEZ® AEWC11 NNB</nameOfTheProduct>
            <picture size="3" pictureAltText="Снимка на лицевата страна на китарата">images/ibanez/ibanez_1.jpg</picture>
            <descriptionOfProduct>
                Възползвайте се от нашето предложение за отлична акустична китара с марката Epiphone.
                Dreadnought китарите са известни със своята благозвучност и насоченост за блус изпълнения,
                кънтри и блуграс, и за страхотен акомпанимент при пеене пред малка публика или на голяма сцена.
                Начинаещи или професионалисти – всеки може да оцени чудесния тон и
                олекотеното усещане при свирене с тази китара.
            </descriptionOfProduct>
            <features>
                <body>
                    <bodyMaterial>Махагон</bodyMaterial>
                    <bodyShape>AEWC тяло</bodyShape>
                    <bodyFinish>Гланц Полиуретан</bodyFinish>
                </body>
                <neck>
                    <neckMaterial>Клен</neckMaterial>
                    <neckFinish>Сатенен уретан с гланцово уретаново лице</neckFinish>
                    <neckShape>AEWC/Nyatoh</neckShape>
                    <scaleLength>63.4 cm</scaleLength>
                    <fingerboardMaterial>Палисандрово дърво</fingerboardMaterial>
                    <fingerboardRadius>400мм</fingerboardRadius>
                    <numberOfFrets>20</numberOfFrets>
                    <fretSize>Jumbo</fretSize>
                    <nutMaterial>Костен</nutMaterial>
                    <nutWidth>(43 mm)</nutWidth>
                    <positionInlays>7мм</positionInlays>
                    <trussRod>None</trussRod>
                </neck>
                <electronics>
                    <neckPickup>Fishman® Sonicore</neckPickup>
                    <controls>Tone Control: x1
                        Volume Control: x1
                    </controls>
                    <switching>5-Way Pickup Selector Switch</switching>
                    <configuration>PK</configuration>
                </electronics>
                <hardware>
                    <bridge>Орехов AEWC оригинален</bridge>
                    <hardwareFinish>Черен цвят</hardwareFinish>
                    <tuningMachines>Хромова die-cast тунери</tuningMachines>
                    <pickguard>3-слойно черен/бял</pickguard>
                    <controlKnobs>Плосък връх, Бял тон</controlKnobs>
                    <neckPlate>Cavity plate, Jack Black</neckPlate>
                </hardware>
                <miscellaneous>
                    <strings>Ibanez IACS6C, .012/.016/.024/.032/.042/.053, 11mm</strings>
                    <legalNotice>
                        ПРЕДУПРЕЖДЕНИЕ: Рак и репродуктивно увреждане - www.P65Warnings.ca.gov .
                    </legalNotice>
                </miscellaneous>
                <accessories gigBag="Yes" guitarPicks="No">Елитен калъф</accessories>
            </features>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>520,00лв.</price>
            <version>#: 0288456300</version>
        </product>
        <product certificate="Yes" returns="Yes">
            <nameOfTheProduct>IBANEZ® V205SECE-NT</nameOfTheProduct>
            <picture size="3" pictureAltText="Снимка на лицевата странан на китарата">images/ibanez/ibanez_3.jpg</picture>
            <descriptionOfProduct>
                Възползвайте се от нашето предложение за отлична акустична китара с марката Ibanez,
                която бързо разрешава задачата да намерите качество, дизайн и звук на отлична цена и за начинаещи.
                Независимо дали търсите традиционен класически инструмент или удобна акустична китара с която да
                започнете, моделите, които предлагаме са изключително добре изработени, достъпни са,
                имат първична тоналност и комфорт при свирене характерни за много по-скъпи китари.
            </descriptionOfProduct>
            <warranty>images/ibanez/Ibanez.pdf</warranty>
            <price>507.00лв.</price>
            <version>#: 0288456170</version>
        </product>
    </products>
</catalogue>
